import test, { before, after } from 'node:test';
import assert from 'node:assert/strict';
import express from 'express';
import cookieParser from 'cookie-parser';
import request from 'supertest';
import { MongoMemoryServer } from 'mongodb-memory-server';
import { MongoClient } from 'mongodb';
import { createAuth, ageDetails, drainMailOutbox } from '../src/auth.js';

let mongo, client, db, app, auth;
const mail = [];
const sendMail = async (message) => { mail.push(message); };
const origin = 'http://localhost:3000';
const account = { username: 'PilotOne', email: 'pilot@example.test', password: 'a sufficiently long passphrase!', dateOfBirth: '2000-03-14' };
const post = (path, body, cookie) => { const req = request(app).post(`/api/auth${path}`).set('Origin', origin).send(body); return cookie ? req.set('Cookie', cookie) : req; };
const cookieOf = (response) => response.headers['set-cookie'].at(-1).split(';')[0];
before(async () => {
  mongo = await MongoMemoryServer.create();
  client = await MongoClient.connect(mongo.getUri()); db = client.db('auth-tests');
  auth = await createAuth({ db, config: { appOrigin: origin }, sendMail });
  app = express(); app.use(express.json(), cookieParser()); app.use('/api/auth', auth.router);
  app.get('/private', auth.authenticate, auth.requireUser, (req, res) => res.json({ id: req.user._id }));
});
after(async () => { await client?.close(); await mongo?.stop(); });

test('age gates reject invalid and underage dates and retain only transition date', () => {
  const now = new Date('2026-09-20T12:00:00Z');
  assert.equal(ageDetails('2013-09-21', now), null);
  assert.equal(ageDetails('2010-02-30', now), null);
  assert.deepEqual(ageDetails('2000-01-01', now), { ageBand: 'adult' });
  assert.equal(ageDetails('2013-09-20', now).ageBand, 'teen');
});
test('register, password verification, origin enforcement, cookie rotation and authorization', async () => {
  assert.equal((await post('/register', { ...account, dateOfBirth: new Date().toISOString().slice(0, 10) })).status, 400);
  assert.equal((await request(app).post('/api/auth/register').set('Origin', 'https://evil.example').send(account)).status, 403);
  const registration = await post('/register', account);
  assert.equal(registration.status, 201);
  assert.equal(registration.body.user.emailVerified, false);
  assert.equal(registration.body.user.passwordHash, undefined);
  const cookie = cookieOf(registration);
  assert.match(registration.headers['set-cookie'].at(-1), /HttpOnly/);
  assert.match(registration.headers['set-cookie'].at(-1), /SameSite=Strict/);
  const user = await db.collection('users').findOne({ usernameKey: 'pilotone' });
  assert.match(user.passwordHash, /^scrypt\$131072\$8\$1\$/);
  assert.equal(user.dateOfBirth, undefined);
  assert.equal((await request(app).get('/private')).status, 401);
  assert.equal((await request(app).get('/private').set('Cookie', cookie)).status, 200);
  assert.equal((await post('/login', { identifier: account.email, password: 'incorrect password' })).status, 401);
  const login = await post('/login', { identifier: 'PILOTONE', password: account.password }, cookie);
  assert.equal(login.status, 200);
  const rotated = cookieOf(login); assert.notEqual(rotated, cookie);
  assert.equal(await auth.resolveSession(cookie), null);
  assert.equal((await auth.resolveSession(rotated))._id, user._id);
  await db.collection('sessions').updateMany({ userId: user._id }, { $set: { expiresAt: new Date(0) } });
  assert.equal(await auth.resolveSession(rotated), null);
});
test('verification and recovery links remain secret, are single use, and reset revokes sessions', async () => {
  assert.equal(mail.length, 0);
  assert.equal((await drainMailOutbox({ db, sendMail })).sent, 1);
  const verify = mail.find((m) => m.subject.includes('Verify')).text.match(/verify-email=([\w-]+)/)[1];
  assert.equal((await post('/verify-email', { token: verify })).status, 200);
  assert.equal((await post('/verify-email', { token: verify })).status, 400);
  const login = await post('/login', { identifier: account.email, password: account.password });
  const cookie = cookieOf(login);
  const forgotten = await post('/forgot-password', { email: account.email });
  const unknown = await post('/forgot-password', { email: 'absent@example.test' });
  assert.deepEqual(forgotten.body, unknown.body);
  assert.equal(mail.length, 1);
  const drained = await drainMailOutbox({ db, sendMail });
  assert.equal(drained.sent, 1);
  assert.equal(drained.skipped, 1);
  const reset = mail.find((m) => m.subject.includes('Reset')).text.match(/reset-password=([\w-]+)/)[1];
  assert.equal(JSON.stringify(forgotten.body).includes(reset), false);
  assert.equal(await db.collection('accountLinks').findOne({ _id: reset }), null);
  const replacement = 'a replacement long passphrase!';
  assert.equal((await post('/reset-password', { token: reset, password: replacement })).status, 200);
  assert.equal(await auth.resolveSession(cookie), null);
  assert.equal((await post('/reset-password', { token: reset, password: replacement })).status, 400);
  assert.equal((await post('/login', { identifier: account.email, password: account.password })).status, 401);
  const next = await post('/login', { identifier: account.email, password: replacement });
  assert.equal(next.status, 200);
  assert.equal(next.body.user.emailVerified, true);
  assert.equal((await post('/logout', {}, cookieOf(next))).status, 200);
  assert.equal(await auth.resolveSession(cookieOf(next)), null);
});
test('outbox leases prevent concurrent delivery, recover stale workers, retry and expire', async () => {
  const outbox = db.collection('mailOutbox');
  // This recipient is eligible independently of suspension tests.
  await db.collection('users').insertOne({ _id: 'outbox-user', usernameKey: 'outbox', emailKey: 'outbox@example.test', email: 'outbox@example.test', authVersion: 0 });
  const insert = (id, overrides = {}) => outbox.insertOne({ _id: id, emailKey: 'outbox@example.test', purpose: 'reset', origin, status: 'queued', attempts: 0, nextAttemptAt: new Date(0), leaseUntil: new Date(0), expiresAt: new Date(Date.now() + 600000), ...overrides });
  await insert('concurrent');
  let sent = 0;
  const deliver = async () => { sent++; await new Promise((resolve) => setTimeout(resolve, 30)); };
  const concurrent = await Promise.all([drainMailOutbox({ db, sendMail: deliver }), drainMailOutbox({ db, sendMail: deliver })]);
  assert.equal(sent, 1); assert.equal(concurrent.reduce((n, result) => n + result.sent, 0), 1);
  const completed = await outbox.findOne({ _id: 'concurrent' });
  assert.equal(completed.emailKey, undefined);
  await insert('retry');
  assert.equal((await drainMailOutbox({ db, sendMail: async () => { throw new Error('provider secret failure'); } })).retried, 1);
  assert.equal((await drainMailOutbox({ db, sendMail: deliver })).sent, 0);
  assert.equal(JSON.stringify(await outbox.findOne({ _id: 'retry' })).includes('provider secret'), false);
  await outbox.updateOne({ _id: 'retry' }, { $set: { nextAttemptAt: new Date(0), status: 'sending', leaseUntil: new Date(0) } });
  assert.equal((await drainMailOutbox({ db, sendMail: deliver })).sent, 1);
  await insert('expired', { expiresAt: new Date(0) });
  await insert('final-failure', { attempts: 4 });
  assert.equal((await drainMailOutbox({ db, sendMail: async () => { throw new Error('no'); } })).failed, 1);
  assert.equal((await drainMailOutbox({ db, sendMail: deliver })).sent, 0);
  assert.equal((await outbox.findOne({ _id: 'expired' }))?.attempts ?? 0, 0);
});
test('suspension and authVersion revocation reject existing sessions immediately', async () => {
  const user = await db.collection('users').findOne({ usernameKey: 'pilotone' });
  const login = await post('/login', { identifier: account.email, password: 'a replacement long passphrase!' });
  const cookie = cookieOf(login);
  await db.collection('users').updateOne({ _id: user._id }, { $set: { suspended: true } });
  assert.equal(await auth.resolveSession(cookie), null);
  assert.equal((await post('/login', { identifier: account.email, password: 'a replacement long passphrase!' })).status, 401);
});
